name: lyc_clinic
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^6.0.0
  shared_preferences: ^0.4.0
  xbanner: ^0.0.3
  video_player: ^0.3.0
  square_calendar: ^0.1.1
  flutter_search_bar: ^2.0.3
  material_search: ^0.2.4
  search_bar: ^1.0.1
  url_launcher: ^3.0.1
  share: ^0.4.0
  path_provider: ^0.4.0
  image_picker: ^0.4.1
  map_view: ^0.0.12
  http: ^0.11.3+16
  json_annotation: ^0.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.9
  json_serializable: ^0.5.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/lyc.png
  - assets/images/1.png
  - assets/images/2.png
  - assets/images/3.png
  - assets/images/4.png
  - assets/videos/1.mp4
  - assets/images/lyc_icon.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Zawgyi-One
    fonts:
      - asset: fonts/Zawgyi-One-20060620.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
